### ISSUE TITLE
Create mission to bag the buoys (deep learning)

### ISSUE THREAD

**Issue by kaowilly** [sonia-auv/sonia-behaviors#10]
**Warning :** Before creating an issue or task, make sure that it does not already exists in the [issue tracker](../). Thank you.

## Comments
Refer to Lucas's plan file (.pdf) in Teams.

**Comment by kaowilly** [comment]
I need to investigate on why when I create a behavior parameter, float values aren't accepted in the "Runtime Control" tab.
Temporary solution as of now is to put the float values directly in every single state where it is needed.

During the pool test on May 21st, I had problems with the run, specifically with the _send_to_planner_ and _wait_target_ states. By removing them, the mission worked.

**Comment by Kam0ss** [comment]
> During the pool test on May 21st, I had problems with the run, specifically with the _send_to_planner_ and _wait_target_ states. By removing them, the mission worked.

This needs to be another issue in proc_planner and proc_control

**Comment by Kam0ss** [comment]
Send_to_planner and wait_target will be tested in Alonzo's pool tonight (31/05)

**Comment by kaowilly** [comment]
There were no problems testing this mission. I confirm that the bagging state don't work on the AUVs but works locally.
I would like to also add Francis's **module_check state** as my next step for this, or should we just make a pull request of what we have now? @Kam0ss
